CC = gcc
CFLAGS = -Wall 
 
objs = ppos_core.o
 
all: tasks teste1 teste2 teste3

tasks: $(objs)

teste1: $(objs)

teste2: $(objs)

teste3: $(objs)

clean:
	-rm -f $(objs) *~
 
purge: clean
	-rm -f tasks teste1 teste2 teste3